/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package evaluacion2;

import javax.swing.JOptionPane;

/**
 *
 * @author labc205
 */
public class Formulario extends javax.swing.JFrame {
    
    num numa = new num();
    num2 numo = new num2();

    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pInciso1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfNum1 = new javax.swing.JTextField();
        jbValidar = new javax.swing.JButton();
        jbImpares = new javax.swing.JButton();
        jbPares = new javax.swing.JButton();
        pInciso5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jtfEmpleado3 = new javax.swing.JTextField();
        jcbCargo3 = new javax.swing.JComboBox<>();
        jtfNum5 = new javax.swing.JTextField();
        jbAgregar3 = new javax.swing.JButton();
        jbAumentar13 = new javax.swing.JButton();
        jbAumentar14 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pInciso1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pInciso1.setToolTipText("");

        jLabel1.setText("Ingrese un #:");

        jbValidar.setText("Agregar");
        jbValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbValidarActionPerformed(evt);
            }
        });

        jbImpares.setText("Mostrar # Impares");
        jbImpares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbImparesActionPerformed(evt);
            }
        });

        jbPares.setText("Mostrar # Pares");
        jbPares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbParesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pInciso1Layout = new javax.swing.GroupLayout(pInciso1);
        pInciso1.setLayout(pInciso1Layout);
        pInciso1Layout.setHorizontalGroup(
            pInciso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInciso1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pInciso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pInciso1Layout.createSequentialGroup()
                        .addComponent(jbPares, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbImpares, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pInciso1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbValidar)))
                .addContainerGap(199, Short.MAX_VALUE))
        );
        pInciso1Layout.setVerticalGroup(
            pInciso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInciso1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pInciso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfNum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbValidar))
                .addGap(18, 18, 18)
                .addGroup(pInciso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbImpares)
                    .addComponent(jbPares))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pInciso5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel11.setText("Empleado:");

        jLabel12.setText("Cargo:");

        jLabel13.setText("Salario:");

        jcbCargo3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Analista", "Programador", "Secretario", "Administrador", " " }));

        jtfNum5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfNum5.setText("0.00");

        jbAgregar3.setText("Agregar");
        jbAgregar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregar3ActionPerformed(evt);
            }
        });

        jbAumentar13.setText("Aumentar los salarios de los Programadores en un 10%");

        jbAumentar14.setText("Aumentar en un 7% los salarios de los empleado que no sean Programador");
        jbAumentar14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAumentar14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pInciso5Layout = new javax.swing.GroupLayout(pInciso5);
        pInciso5.setLayout(pInciso5Layout);
        pInciso5Layout.setHorizontalGroup(
            pInciso5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInciso5Layout.createSequentialGroup()
                .addGroup(pInciso5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pInciso5Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(pInciso5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(pInciso5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pInciso5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jtfEmpleado3)
                                .addComponent(jcbCargo3, 0, 215, Short.MAX_VALUE))
                            .addComponent(jtfNum5, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pInciso5Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(pInciso5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbAumentar13)
                            .addComponent(jbAgregar3)
                            .addComponent(jbAumentar14))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pInciso5Layout.setVerticalGroup(
            pInciso5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInciso5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pInciso5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jtfEmpleado3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pInciso5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jcbCargo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pInciso5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jtfNum5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbAgregar3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbAumentar13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbAumentar14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pInciso1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pInciso5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pInciso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pInciso5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbValidarActionPerformed
        // TODO add your handling code here:
        int num1 = Integer.parseInt(jtfNum1.getText());
        numa.myNum(num1);
        jtfNum1.setText("");
        jtfNum1.requestFocus();
    }//GEN-LAST:event_jbValidarActionPerformed

    private void jbParesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbParesActionPerformed
        // TODO add your handling code here:
        int s = numa.numsize(); 
        for(int a = 0; a < s; a++){
            if(numa.getnum(a) % 2 == 0){
                JOptionPane.showMessageDialog(this, numa.getnum(a), "Salida", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_jbParesActionPerformed

    private void jbAumentar14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAumentar14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbAumentar14ActionPerformed

    private void jbImparesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbImparesActionPerformed
        // TODO add your handling code here:
        int s = numa.numsize(); 
        for(int a = 0; a < s; a++){
            if(numa.getnum(a) % 2 != 0){
                JOptionPane.showMessageDialog(this, numa.getnum(a), "Salida", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_jbImparesActionPerformed

    private void jbAgregar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregar3ActionPerformed
        // TODO add your handling code here:
        double salario = Double.parseDouble(jtfNum5.getText());
        String nom = jtfEmpleado3.getText();
        Cargo s;
        if (jcbCargo3.getSelectedIndex() == 1) s = Cargo.Analista;
        else if (jcbCargo3.getSelectedIndex() == 2) s = Cargo.Programador;
        else if (jcbCargo3.getSelectedIndex() == 3) s = Cargo.Secretario;
        else if (jcbCargo3.getSelectedIndex() == 4) s = Cargo.Administrador;
        else JOptionPane.showMessageDialog(this, "Seleccione una de las opciones dadas", "Error", JOptionPane.INFORMATION_MESSAGE);
        
        int b = numo.agregarPersona(salario, nom, s);
        if (b==1) {
            JOptionPane.showMessageDialog(this, "Registro Agregado",
                    "Guardar", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Error al guardar...", "Guardar", JOptionPane.ERROR);
        }
        
        jtfNum5.setText("");
        jtfEmpleado3.setText("0.00");
        jcbCargo.setSelectedIndex(0);
        
    }//GEN-LAST:event_jbAgregar3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jbAgregar;
    private javax.swing.JButton jbAgregar1;
    private javax.swing.JButton jbAgregar2;
    private javax.swing.JButton jbAgregar3;
    private javax.swing.JButton jbAumentar10;
    private javax.swing.JButton jbAumentar11;
    private javax.swing.JButton jbAumentar12;
    private javax.swing.JButton jbAumentar13;
    private javax.swing.JButton jbAumentar14;
    private javax.swing.JButton jbAumentar7;
    private javax.swing.JButton jbAumentar8;
    private javax.swing.JButton jbAumentar9;
    private javax.swing.JButton jbImpares;
    private javax.swing.JButton jbPares;
    private javax.swing.JButton jbValidar;
    private javax.swing.JComboBox<String> jcbCargo;
    private javax.swing.JComboBox<String> jcbCargo1;
    private javax.swing.JComboBox<String> jcbCargo2;
    private javax.swing.JComboBox<String> jcbCargo3;
    private javax.swing.JTextField jtfEmpleado;
    private javax.swing.JTextField jtfEmpleado1;
    private javax.swing.JTextField jtfEmpleado2;
    private javax.swing.JTextField jtfEmpleado3;
    private javax.swing.JTextField jtfNum1;
    private javax.swing.JTextField jtfNum2;
    private javax.swing.JTextField jtfNum3;
    private javax.swing.JTextField jtfNum4;
    private javax.swing.JTextField jtfNum5;
    private javax.swing.JPanel pInciso1;
    private javax.swing.JPanel pInciso2;
    private javax.swing.JPanel pInciso3;
    private javax.swing.JPanel pInciso4;
    private javax.swing.JPanel pInciso5;
    // End of variables declaration//GEN-END:variables
}
